apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-app-deployment
  labels:
    app: notifications-app
spec:
  selector:
    matchLabels:
      app: notifications-app
  template:
    metadata:
      labels:
        app: notifications-app
    spec:
      containers:
        - name: notifications-app
          image: matheusjustino/sword-health-challenge-notifications-api
          ports:
            - containerPort: 8081
          env:
            - name: RABBITMQ_USER
              valueFrom:
                configMapKeyRef:
                  name: notifications-app-envs
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: notifications-app-envs
                  key: RABBITMQ_PASSWORD
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: notifications-app-envs
                  key: RABBITMQ_HOST
            - name: NOTIFICATIONS_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: notifications-app-envs
                  key: NOTIFICATIONS_QUEUE
