apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- development.yml
- service.yml
namespace: argocd
images:
- name: matheusjustino/sword-health-challenge-notifications-api
  newName: matheusjustino/sword-health-challenge-notifications-api
  newTag: c3965f1699213d02b1dd3e6473e8890ce87e5703
