apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- development.yml
- service.yml

namespace: argocd

images:
- name: matheusjustino/sword-health-challenge-notifications-api
  newName: matheusjustino/sword-health-challenge-notifications-api
  newTag: 64a525fec9368c4c33fd8f2f2ecb69c97f300283
