apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- notifications-api
- users-api

namespace: argocd
images:
- name: matheusjustino/sword-health-challenge-notifications-api
  newName: matheusjustino/sword-health-challenge-notifications-api
  newTag: 90a30de0b5d73a7f1a5950cd6172a03bf6846960
- name: matheusjustino/sword-health-challenge-users-api
  newName: matheusjustino/sword-health-challenge-users-api
  newTag: 90a30de0b5d73a7f1a5950cd6172a03bf6846960
