apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-app-deployment
  labels:
    app: users-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-app
  template:
    metadata:
      labels:
        app: users-app
    spec:
      containers:
        - name: users-app
          image: matheusjustino/sword-health-challenge-users-api
          ports:
            - containerPort: 8080
          args: ["-c", "./entrypoint.sh"]
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: users-app-envs
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: users-app-envs
                  key: PORT
            - name: SECRET
              valueFrom:
                configMapKeyRef:
                  name: users-app-envs
                  key: SECRET
            - name: RABBITMQ_USER
              valueFrom:
                configMapKeyRef:
                  name: users-app-envs
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: users-app-envs
                  key: RABBITMQ_PASSWORD
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: users-app-envs
                  key: RABBITMQ_HOST
            - name: NOTIFICATIONS_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: users-app-envs
                  key: NOTIFICATIONS_QUEUE
            - name: DB_TYPE
              valueFrom:
                configMapKeyRef:
                  name: users-app-envs
                  key: DB_TYPE
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: users-app-envs
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: users-app-envs
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: users-app-envs
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: users-app-envs
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: users-app-envs
                  key: NOTIFICATIONS_QUEUE
