name: CD
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push (sword-health-challenge-users-api)
        uses: docker/build-push-action@v2
        with:
          context: ./users-api
          push: true
          tags: |
            matheusjustino/sword-health-challenge-users-api:${{ github.sha }}
            matheusjustino/sword-health-challenge-users-api:latest

      - name: Build and push (sword-health-challenge-notifications-api)
        uses: docker/build-push-action@v2
        with:
          context: ./notifications-api
          push: true
          tags: |
            matheusjustino/sword-health-challenge-notifications-api:${{ github.sha }}
            matheusjustino/sword-health-challenge-notifications-api:latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize_version: v3.6.1

      - name: Update k8s
        run: |
          cd k8s
          kustomize edit set image matheusjustino/sword-health-challenge-users-api=matheusjustino/sword-health-challenge-users-api:${{ github.sha }}
          kustomize edit set image matheusjustino/sword-health-challenge-notifications-api=matheusjustino/sword-health-challenge-notifications-api:${{ github.sha }}
          cat kustomization.yaml
      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Deploy Action"
          git commit -am "Change image tag"
      - name: Push
        uses: ad-m/github-push-action@master
