name: CD
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize_version: v3.6.1

      - name: Update k8s
        run: |
          cd k8s/users-api
          kustomize edit set image matheusjustino/sword-health-challenge-users-api=matheusjustino/sword-health-challenge-users-api:${{ github.sha }}
          cat kustomization.yml
          cd ../notifications-api
          kustomize edit set image matheusjustino/sword-health-challenge-notifications-api=matheusjustino/sword-health-challenge-notifications-api:${{ github.sha }}
          cat kustomization.yml
      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Deploy Action"
          git commit -am "Change image tag"
      - name: Push
        uses: ad-m/github-push-action@master
